<template>
  <div class="leading-normal tracking-normal text-gray-900 h-screen">
    <div class="pb-14 bg-right bg-cover md:h-full" style="background-image:url('img/bg.svg');">
      <!--Nav-->
      <MarketingSiteNavigation />
      <!--Main-->
      <div
        class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center"
      >
        <!--Left Col-->
        <div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
          <h1
            class="my-4 text-3xl md:text-5xl text-purple-800 font-bold leading-tight text-center md:text-left slide-in-bottom-h1"
          >Easy to use project management app</h1>
          <p
            class="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle"
          >Real time collaboration and much more</p>

          <p
            class="text-indigo-600 text-lg font-bold pb-8 lg:pb-6 text-center md:text-left fade-in"
          >Get Started</p>
          <div class="flex w-full justify-center md:justify-start pb-24 lg:pb-0 fade-in">
            <router-link
              to="/register"
              class="px-2 py-2 text-sm font-medium text-white bg-purple-600 rounded hover:bg-purple-700"
            >Create an account</router-link>
          </div>
        </div>

        <!--Right Col-->
        <div class="w-full xl:w-3/5 py-6 overflow-y-hidden"></div>

        <!--Footer-->
        <TheFooter />
      </div>
    </div>
  </div>
</template>

<script>
import TheFooter from '../components/reusables/TheFooter';
import MarketingSiteNavigation from '../components/MarketingSiteNavigation';
export default {
  name: 'home',
  components: {
    MarketingSiteNavigation,
    TheFooter
  },
  beforeRouteEnter(to, from, next) {
    next(vueInstance => {
      if (to.query.logout) {
        vueInstance.$store.dispatch('logout');
      }
    });
  }
};
</script>

<style scoped>
/* ----------------------------------------------
	* Generated by Animista
  * w: http://animista.net, t: @cssanimista
	* ---------------------------------------------- */

.slide-in-bottom {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.slide-in-bottom-h1 {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.5s both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
}
.slide-in-bottom-subtitle {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.75s both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.75s
    both;
}
.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) 1s both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) 1s both;
}

@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>