const authRoutes = require('./routes/auth');
const boardRoutes = require('./routes/board');
const listRoutes = require('./routes/list');
const cardRoutes = require('./routes/card');
const commentRoutes = require('./routes/comment');
const labelRoutes = require('./routes/label');
const labelCardRoutes = require('./routes/labelCard');
const attachmentRoutes = require('./routes/attachment');
const userBoardRoutes = require('./routes/userBoard');
const userCardRoutes = require('./routes/userCard');
const userSearchRoutes = require('./routes/userSearch');
const listOrderRoutes = require('./routes/listOrder');
const cardOrderRoutes = require('./routes/cardOrder');
const archiveCardRoutes = require('./routes/archiveCard');
const teamRoutes = require('./routes/team.routes');
const teamUserRoutes = require('./routes/teamUser.routes');
const teamBoardRoutes = require('./routes/teamBoard.routes');
const boardSearchRoutes = require('./routes/boardSearch.routes');
const userRoutes = require('./routes/user.routes');
const emailRoutes = require('./routes/email.routes');

module.exports = app => {
  app.use('/api/auth', authRoutes);
  app.use('/api/user', userRoutes);
  app.use('/api/board/search', boardSearchRoutes);
  app.use('/api/board/user', userBoardRoutes);
  app.use('/api/board', boardRoutes);
  app.use('/api/list', listRoutes);
  app.use('/api/card', cardRoutes);
  app.use('/api/comment', commentRoutes);
  app.use('/api/label', labelRoutes);
  app.use('/api/label/card', labelCardRoutes);
  app.use('/api/attachment', attachmentRoutes);
  app.use('/api/card/user', userCardRoutes);
  app.use('/api/list/order', listOrderRoutes);
  app.use('/api/card/order', cardOrderRoutes);
  app.use('/api/card/archive', archiveCardRoutes);
  app.use('/api/user/search', userSearchRoutes);
  app.use('/api/team', teamRoutes);
  app.use('/api/team/user', teamUserRoutes);
  app.use('/api/team/board', teamBoardRoutes);
  app.use('/api/user/email', emailRoutes);
};
