<template>
  <nav class="w-full container mx-auto p-6">
    <div class="w-full flex flex-col sm:flex-row items-center justify-between">
      <router-link
        class="fade-in flex items-center text-indigo-700 font-bold text-2xl lg:text-4xl hover:text-indigo-900"
        to="/"
      >
        <svg class="h-8 fill-current pr-2" viewBox="0 0 20 20">
          <path
            d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm-5.6-4.29a9.95 9.95 0 0 1 11.2 0 8 8 0 1 0-11.2 0zm6.12-7.64l3.02-3.02 1.41 1.41-3.02 3.02a2 2 0 1 1-1.41-1.41z"
          />
        </svg>
        <span>Trackerify</span>
      </router-link>

      <div class="flex justify-end content-center items-center">
        <router-link
          v-if="!isUserLoggedIn"
          to="/register"
          class="inline-block font-semibold text-blue-600 hover:text-indigo-800 text-center h-10 p-2 md:h-auto md:p-4 hover:underline fade-in"
        >Register</router-link>
        <router-link
          v-if="!isUserLoggedIn"
          to="/login"
          class="inline-block font-semibold text-blue-600 hover:text-indigo-800 text-center h-10 p-2 md:h-auto md:p-4 hover:underline fade-in"
        >Login</router-link>
        <router-link
          v-if="isUserLoggedIn"
          to="/board"
          class="inline-block font-semibold text-blue-600 hover:text-indigo-800 text-center h-10 p-2 md:h-auto md:p-4 hover:underline fade-in"
        >Board Overview</router-link>
        <button
          v-if="isUserLoggedIn"
          @click="$store.dispatch('logout')"
          class="inline-block font-semibold text-blue-600 hover:text-indigo-800 text-center h-10 p-2 md:h-auto md:p-4 hover:underline fade-in"
        >Logout</button>
        <a
          class="inline-block text-blue-300 no-underline hover:text-indigo-800 text-center h-10 p-2 md:h-auto md:p-4 fade-in"
          href="https://github.com/jacobmolby/Trackerify"
        >
          <svg class="fill-current h-6" viewBox="0 0 24 24">
            <title>GitHub Page</title>
            <path
              d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
            />
          </svg>
        </a>
      </div>
    </div>
  </nav>
</template>

<script>
import { mapState } from 'vuex';
export default {
  name: 'MarketingSiteNavigation',
  computed: {
    ...mapState(['isUserLoggedIn'])
  }
};
</script>

<style scoped>
/* ----------------------------------------------
	* Generated by Animista
  * w: http://animista.net, t: @cssanimista
	* ---------------------------------------------- */

.slide-in-bottom {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.slide-in-bottom-h1 {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.5s both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
}
.slide-in-bottom-subtitle {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.75s both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.75s
    both;
}
.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) 1s both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) 1s both;
}

@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>