<template>
  <transition
    name="slide-fade"
    enter-active-class="flip-in-hor-top"
    leave-active-class="flip-out-hor-bottom"
  >
    <div v-if="showing" class="z-50 modal bg-gray-800 p-3 rounded min-w-64 max-w-4xl shadow-md">
      <span
        style="text-overflow: ellipsis; white-space: nowrap;"
        class="overflow-hidden w-full block font-semibold"
        :class="type == 'error' ? 'text-red-500' : 'text-white'"
      >{{message}}</span>
    </div>
  </transition>
</template>

<script>
import { mapState } from 'vuex';
export default {
  computed: {
    ...mapState({
      showing: state => state.modal.showing,
      message: state => state.modal.message,
      type: state => state.modal.type
    })
  }
};
</script>

<style>
.modal {
  position: absolute;
  top: 90%;
  left: 5%;
}
.flip-in-hor-top {
  -webkit-animation: flip-in-hor-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: flip-in-hor-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.flip-out-hor-bottom {
  -webkit-animation: flip-out-hor-bottom 0.45s
    cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  animation: flip-out-hor-bottom 0.45s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-2-7 23:23:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-in-hor-top
 * ----------------------------------------
 */
@-webkit-keyframes flip-in-hor-top {
  0% {
    -webkit-transform: rotateX(-80deg);
    transform: rotateX(-80deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
    opacity: 1;
  }
}
@keyframes flip-in-hor-top {
  0% {
    -webkit-transform: rotateX(-80deg);
    transform: rotateX(-80deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-2-7 23:24:38
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-out-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes flip-out-hor-bottom {
  0% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: rotateX(-70deg);
    transform: rotateX(-70deg);
    opacity: 0;
  }
}
@keyframes flip-out-hor-bottom {
  0% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: rotateX(-70deg);
    transform: rotateX(-70deg);
    opacity: 0;
  }
}
</style>